### ISSUE TITLE
SB 1.5 is EOL now. Updated example?

### ISSUE THREAD

**Issue by mballoni** [oktadev/okta-spring-boot-saml-example#10]
Spring boot 1.x has reached EOL:

https://spring.io/blog/2019/08/06/it-is-time-goodbye-spring-boot-1-x

 Also, the library "spring-security-saml-dsl" does not see an updated version for almost two years and is probably in maintenance mode since most extensions of spring security are being rewritten and incorporated in spring security.

 Would it be possible to provide an example with updated versions (Spring Boot 2.1.x) and maybe that does not rely on the dependency described above?

**Comment by mraible** [comment]
Thank you for your request @mballoni! We've added an update to this post as an idea for a future post.

**Comment by mraible** [comment]
In the meantime, you might try using [Spring Security's new built-in SAML support](https://docs.spring.io/spring-security/site/docs/5.2.1.RELEASE/reference/htmlsingle/#saml2).
