### ISSUE TITLE
Issue with saml method

### ISSUE THREAD

**Issue by ipawanktiwari** [oktadev/okta-spring-boot-saml-example#15]
The saml() is not supported in spring boot 2.x. Please update code or kindly drop a link so that we can move in a right direction.

https://github.com/oktadeveloper/okta-spring-boot-saml-example/blob/e2edc1ed024f27a9b154bb789b448ba4994e779e/src/main/java/com/example/demo/SecurityConfiguration.java#L38

**Comment by mraible** [comment]
We published a new tutorial on Spring Boot and SAML this week. See
https://developer.okta.com/blog/2020/10/14/spring-security-saml-database-authentication.
Please let us know if it helps.

**Comment by ipawanktiwari** [comment]
Hi @mraible , Thanks for response. Yeah it had helped me to understand the flow and I've successfully integrated it in my application. So thank you.

**Comment by mraible** [comment]
That's great to hear! I'm closing this issue since your problem seems to be fixed. 🙂
