### ISSUE TITLE
Not finding Service provider meta data

### ISSUE THREAD

**Issue by sasmitapatipinki** [oktadev/okta-spring-boot-saml-example#16]
while i import your application and run i did not getting my application(service provider application)meta data
how to getting service provider meta data

**Comment by mraible** [comment]
Did you follow the steps in this project's README or its associated blog post. If so, and it didn't work for you, I'd recommend this more recent tutorial:

https://developer.okta.com/blog/2020/10/14/spring-security-saml-database-authentication

**Comment by mraible** [comment]
Closing since this repo will be updated with a new example soon. See #17 for more information.
