### ISSUE TITLE
The sample project is not handling the initial OPTIONS request sent out by Okta.

### ISSUE THREAD

**Issue by tommai78101** [oktadev/okta-spring-boot-saml-example#29]
I'm making an assumption based on findings from our log messages.

When attempting to authenticate with Okta, Okta first sends out an OPTIONS request to validate if the Destination location configured on the Okta portal supports a POST request or some other request methods, before sending out the request with that supported request method.

This sample project is currently not able to handle the initial OPTIONS request, so it throws an error about `No relying party registration found` for that OPTIONS request in the log messages. 

Can this sample project be updated so we can know how to properly handle this OPTIONS request?

**Comment by mraible** [comment]
Hello @tommai78101. I was the maintainer of this example, but I no longer work at Okta after the Feb 1 layoffs. I'd suggest asking this question on the Okta or Auth0 community forums.

**Comment by tommai78101** [comment]
@mraible Sorry to hear about that. Thank you for the pointers.
