### ISSUE TITLE
can't run it!

### ISSUE THREAD

**Issue by maiziheimei** [oktadev/okta-spring-boot-saml-example#7]
there is an error, I have completely followed your blog.  Could you give me a hint? Thanks!

<img width="619" alt="screen shot 2018-08-01 at 16 37 45" src="https://user-images.githubusercontent.com/25683284/43528461-5790e31a-95a9-11e8-84fa-87814d9e0c78.png">

**Comment by neuzhouyi0117** [comment]
hi, 
i also have the error.
check on the Synchronize Computer Time Settings with Internet.
It will be work.

**Comment by dharmendra25** [comment]
Can Anyone create a new SpringBoot App with SAML2.0 and OKTA  plz....
I am facing issues, while creating SAML2.0 Template App  in OKTA. it's not showing Saml2.0 config in Sign-on Tab.

**Comment by mraible** [comment]
Hello everyone. I'm sorry for not responding sooner - I missed this issue and your comments somehow.

@maiziheimei and @neuzhouyi0117 I just went through [my Spring Boot + SAML](https://developer.okta.com/blog/2017/03/16/spring-boot-saml) tutorial again (using Spring Boot 2.1.3 this time) and everything worked without problems. Can you please try again, or compare your code to the code in this repo? 

[SmartSynchronize](https://www.syntevo.com/smartsynchronize/) is a great tool for comparing directories. I've used [Beyond Compare](https://www.scootersoftware.com/download.php) in the past too.

@dharmendra25 You are correct. Thanks to your comment, I discovered this morning that oktapreview.com orgs do have the SAML option. Accounts on okta.com do NOT. I've reported this to our team. I'll comment on this issue when it's fixed.

**Comment by dharmendra25** [comment]
Thanks @mraible for your quick reply.

I will wait for your response after it get fixed.

**Comment by nbarbettini** [comment]
Hey @dharmendra25 - thanks for reporting this. Can you give me some more info on what you are building with Spring Boot + SAML? Are you adding Okta authentication (via SAML) to an existing app?

**Comment by dharmendra25** [comment]
Hi @nbarbettini,
Thank you for your quick reply.
I was trying to build a simple sping boot web application with OKTA authentication via SAML2.0 by referring @mraible's post but i belive it was with old posts and i didn't get any updated post for OKTA site with new SAML2.0 (deprecated) setup.

It will  be helpful, if you could create a new simple spring boot web application with OKTA authentication via SAML2.0 (deprecated) template.

Thank you for your help in advance.

Please let me know, if you require any more information from my end.

**Comment by mraible** [comment]
@dharmendra25 If you create an account using https://www.okta.com/integrate/signup/, you'll have 1) the classic UI by default, and 2) the ability to create SAML applications. I'm in the process of fixing the post.

**Comment by dharmendra25** [comment]
Hey @mraible ,
I took code from ur hithub link and created an application in okta.
Also chnaged the metadata url in properties file and also generated key.

But after doing all , i am unable to access https://localhost:8443/
Error:
------
org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header

**Comment by mraible** [comment]
Have you tried generating a new certificate? The README in this project shows you how.

**Comment by dharmendra25** [comment]
@mraible
After adding the meta url in the properties file, i used below command to generate keystore in my saml directory:
keytool -genkey -v -keystore keystore.jks -alias spring -keyalg RSA -keysize 2048 -validity 10000

with password "secret".

Is their any thing i left for the setup?

**Comment by mraible** [comment]
I'm not sure what your issue is @dharmendra25. I re-did my tutorial a couple of weeks ago and didn't have any problems.

**Comment by neuzhouyi0117** [comment]
Thanks for you help. the sample source can work now!




At 2019-03-15 00:43:31, "Matt Raible" <notifications@github.com> wrote:


I'm not sure what your issue is @dharmendra25. I re-did my tutorial a couple of weeks ago and didn't have any problems.

**Comment by neuzhouyi0117** [comment]
one more question for help.
how to logout with the sample source code. Can you give me a logout sample source code for studying the saml2.0





At 2019-03-15 00:43:31, "Matt Raible" <notifications@github.com> wrote:


I'm not sure what your issue is @dharmendra25. I re-did my tutorial a couple of weeks ago and didn't have any problems.

**Comment by mraible** [comment]
@neuzhouyi0117 I asked the Spring Security team for a logout example in [May 2017](https://github.com/spring-projects/spring-security-saml-dsl/issues/30). There are comments on that issue that show how to log out. I haven't tried the suggestions myself.
