### ISSUE TITLE
NO Idp

### ISSUE THREAD

**Issue by yuanyaosmile** [oktadev/okta-spring-boot-saml-example#8]
the blog is so detailed. but after i run the application, i visited the page https://lcoalhost:8443, what i got is 500 and No IDP was configured, please update included metadata with at least one IDP. do i did something wrong?

**Comment by mraible** [comment]
If the blog post has too much information, the README of this project has a
simplified version of the instructions:
https://github.com/oktadeveloper/okta-spring-boot-saml-example
