### ISSUE TITLE
How to configure the urls with context path?

### ISSUE THREAD

**Issue by naginenimahesh** [oktadev/okta-spring-boot-saml-example#9]
How can we configure urls with context path in okta and also in Security configuration file.

Ex: https://localhost:8443/myapp/

Also, I am using Spring MVC which has regular spring security authentication using sql written in spring-security.xml.

Now, we want to support okta login for some of the users. Is it possible to do that?

**Comment by mraible** [comment]
If you have a context path, you just need to adjust your redirect URI on Okta to account for it. https://developer.okta.com/blog/2019/04/16/spring-boot-tomcat shows you how to do that.

For your other questions, can you please ask them on our <a href="https://devforum.okta.com/">developer forums</a>? There will be more eyeballs on it if you post it there.
